name: deploy tencent serverless

on:
  push:
    branches:

jobs:
  deploy:
    name: deploy serverless
    runs-on: ubuntu-latest
    steps:
      - name: clone local repository
        uses: actions/checkout@v2
      - name: install serverless
        run: npm install -g serverless
      - name: install dependency
        run: npm install
      - name: build
        run: npm build
      - name: deploy serverless
        run: sls deploy --debug
        env:
          STAGE: dev
          SERVERLESS_PLATFORM_VENDOR: tencent
          TENCENT_SECRET_ID: ${{secrets.TENCENT_SECRET_ID}}
          TENCENT_SECRET_KEY: ${{secrets.TENCENT_SECRET_KEY}}